pipeline {
    agent  any 
    parameters {
       string defaultValue: '/usr/local/bin/terraform', description: '', name: 'terraform_cmd', trim: false
        }

    stages {
        stage('build')  {
            steps {
                git branch: 'feature', changelog: false, poll: false, url: 'git@github.com:rupinder-on-github/CICD-test.git'
            }
        }
        stage('Initialising terraform') {
            steps {

                sh '''
                  cd  terraform
                  $terraform_cmd init
                  ls -lrt
                '''

            }
        }
        stage('Running terraform plan') {
            steps {
                sh '''
                  cd  terraform
                  /usr/local/bin/terraform plan 
                '''
            }
        stage('Running terraform apply') {
            steps {
                sh '''
                  cd  terraform
                  /usr/local/bin/terraform apply 
                '''
            }            
        }
    }
}
