pipeline {
    agent  any 
    stages {
        stage('build') {
            steps {
                git branch: 'feature', changelog: false, poll: false, url: 'git@github.com:rupinder-on-github/CICD-test.git'
            }
        }
        stage('Initialising terraform') {
            parameters {
               string defaultValue: '/usr/local/bin/terraform', description: '', name: 'terraform_cmd', trim: false
               }
            steps {
                sh '''
                  cd  terraform
                  ${terraform_cmd} init
                '''

            }
        }
        stage('Running terraform plan') {
            steps {
                sh '''
                  cd  terraform
                  /usr/local/bin/terraform plan
                '''
            }
        }
    }
}
